site_name: Refget Specifications
site_url: https://ga4gh.github.io/refget
repo_url: https://github.com/ga4gh/refget
copyright: GA4GH Large Scale Genomics Workstream, refget team

nav:
  - Specifications: 
    - Sequences: sequences/README.md
    - Sequence Collections: seqcols/README.md
  - Detailed how-to guides:
    - Compute a digest given a seqcol: seqcols/digest_from_collection.md
    - Compare two sequence collections: seqcols/compare_collections.md
  - Implementations:
    - Python: implementation_python.md
    - API: implementation_api.md
  - Reference:
    - How to cite: citation.md
    - Schemas: schemas/README.md
    - Decision record: decision_record.md
    - Contributing: contributing.md

theme:
  logo: img/seqcol_logo.svg
  favicon: img/seqcol_logo.svg
  name: material

  features:
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.footer
    # - navigation.indexes 
    - toc.follow
    - content.action.edit
    - content.action.view
    # - navigation.tabs
    - navigation.top

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - toc:
      toc_depth: 3
