site_name: Refget Specifications
site_url: https://ga4gh.github.io/refget
repo_url: https://github.com/ga4gh/refget
nav:

  - Specifications: 
    - Sequences: sequences.md
    - Sequence Collections: seqcol.md
  - Detailed how-to guides:
    - Compute a digest given a SeqCol: digest_from_collection.md
    - Retrieve a SeqCol given a digest: sequences_from_digest.md
    - Compare two sequence collections: compare_collections.md
    - Other recipes: recipes.md
  - Implementations:
    - Python: implementation_python.md
    - API: implementation_api.md
  - Reference:
    - Decision record: decision_record.md
    - Contributing: contributing.md


copyright: GA4GH Large Scale Genomics Workstream, Seqcol team
home_link: null
navbar:
  left:
  - text: Specification
    icon: fa-file-alt
    href: specification
  - text: Decision Record
    icon: fa-history
    href: decision_record
  - text: Contributing
    icon: fa-users
    href: contributing

theme:
  logo: img/ga4gh-logo-dark-bg.png
  favicon: img/seqcol_logo.svg
  name: material

  features:
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.footer
    # - navigation.indexes 
    - toc.follow
    - content.action.edit
    - content.action.view
    # - navigation.tabs
    - navigation.top

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - toc:
      toc_depth: 3
